name: iot_botnet_detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - tensorflow
  - matplotlib
  - seaborn
  - pyyaml
  - pip
  - pip:
    - python-dotenv